Add slightly nicer `__repr__`
When using plain `assert snaptolshot == ...`, pytest prints the `repr`, which is
not super helpful and can be quite noisy. This just adds a very simple
`__repr__` implementation to make this a bit easier to read.

Before:

```
E       AssertionError: assert Snapshot(nodeid='test_snap.py::test_default', snapshot_file=PosixPath('/tmp/snaptoltest/__snapshots__/test_snap.py__te...False, rtol=1e-05, atol=1e-08, equal_nan=False, cache=Cache(), config=<_pytest.config.Config object at 0x7f56d1211400>) == array([13.3567, 23.4486, 19.8765])
E        +  where Snapshot(nodeid='test_snap.py::test_default', snapshot_file=PosixPath('/tmp/snaptoltest/__snapshots__/test_snap.py__te...False, rtol=1e-05, atol=1e-08, equal_nan=False, cache=Cache(), config=<_pytest.config.Config object at 0x7f56d1211400>) = Snapshot(nodeid='test_snap.py::test_default', snapshot_file=PosixPath('/tmp/snaptoltest/__snapshots__/test_snap.py__te...False, rtol=1e-05, atol=1e-08, equal_nan=False, cache=Cache(), config=<_pytest.config.Config object at 0x7f56d1211400>)(rtol=1e-05)
```

After:

```
E       assert Snapshot([13.2567, 23.4486, 19.8765]) == array([13.3567, 23.4486, 19.8765])
E        +  where Snapshot([13.2567, 23.4486, 19.8765]) = Snapshot([13.2567, 23.4486, 19.8765])(rtol=1e-05)

```

It would be nice to go further and eliminate the `where` line, but I'm not sure
how to that immediately